version: "3"
services:
  scramjet-hub:
    image: scramjetorg/hub:0.10.0-pre.10
    volumes:
      - /tmp/:/tmp/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    restart: unless-stopped
    command: ["scramjet-transform-hub", "-H", "0.0.0.0"]
